Repository PrestaShopCorp/ps_facebook, pull requests merged in 2022-02, with the labels that each got.

#378 Adding crowdin for translations
  _dev/src/assets/json/translations/de/ui.json
  _dev/src/assets/json/translations/en/ui.json
  _dev/src/assets/json/translations/es/ui.json
  _dev/src/assets/json/translations/fr/ui.json
  _dev/src/assets/json/translations/it/ui.json
  _dev/src/assets/json/translations/nl/ui.json
  _dev/src/assets/json/translations/pl/ui.json
  _dev/src/assets/json/translations/pt/ui.json
  _dev/src/lib/i18n.ts
  _dev/src/lib/translations.ts
  _dev/src/shims-tsx.d.ts
  _dev/src/store/modules/context/index.ts
  _dev/tsconfig.json
  classes/DTO/ConfigurationData.php
  classes/Handler/EventBusProductHandler.php
  classes/Repository/ProductRepository.php
  classes/Translations/PsFacebookTranslations.php
  classes/Translations/index.php
  config/common.yml
  config/common/handler.yml
  config/common/repository.yml
  config/common/translations.yml
  controllers/admin/AdminPsfacebookModuleController.php
  crowdin.yml
  tests/unit/Handler/EventBusProductHandlerTest.php
  tests/utils/generateTranslationsForStorybook.php
  translations/de.php
  translations/en.php
  translations/es.php
  translations/fr.php
  translations/it.php
  translations/nl.php
  translations/pl.php
  translations/pt.php
Labels: Feature, VueJS

#384 Switch on Facebook API version 13
  classes/Config/Config.php
Labels: PHP

#386 Fix availability property in OpenGraph microdata
  views/templates/hook/header.tpl
Labels: bug, PHP

#380 Adding CDN on projet
  .github/workflows/js.yml
  .github/workflows/publish.yml
  README.md
  _dev/vue.config.js
  classes/Config/Config.php
  controllers/admin/AdminPsfacebookModuleController.php
  views/templates/admin/app.tpl
Labels: Feature
